window.SUPABASE_URL = 'https://soyeneligfpjpylwhslt.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNveWVuZWxpZ2ZwanB5bHdoc2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NDkzNDMsImV4cCI6MjA4ODUyNTM0M30.Sla8iRlMEL-8wEFFQIwuqZRtbAOjYRT9i8xntXtH2QQ';
