// scripts/generate-config.js
// Vercel 빌드 시 환경 변수 -> js/config.js 자동 생성

const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('[build] ERROR: SUPABASE_URL 또는 SUPABASE_ANON_KEY 환경 변수가 없습니다.');
  console.error('[build] Vercel Dashboard -> Settings -> Environment Variables 에서 설정하세요.');
  process.exit(1);
}

const content = `// Auto-generated by build script. Do NOT commit.\nwindow.SUPABASE_URL = '${url}';\nwindow.SUPABASE_ANON_KEY = '${key}';\n`;

const outPath = path.join(__dirname, '..', 'js', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[build] js/config.js 생성 완료:', url);
